# Generated by Django 6.0.4 on 2026-05-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='URL to redirect to when clicked', max_length=500),
        ),
    ]
